networks:
    fee-net:
        name: fee-net

services:
    redis:
        image: redis:7-alpine
        command: ["redis-server", "--appendonly", "yes"]
        container_name: fee-redis
        volumes:
            - redis-data:/data
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 5s
            timeout: 2s
            retries: 10
        networks:
            - fee-net

    app:
        image: ${IMAGE}
        container_name: fee-app
        depends_on:
            redis:
                condition: service_healthy
        env_file:
            - .env
        ports:
            - "${PORT:-8787}:${PORT:-8787}"
        restart: unless-stopped
        networks:
            - fee-net

volumes:
    redis-data:
        driver: local
        driver_opts:
            type: none
            device: ./redis-data
            o: bind
